@baseUrl = http://127.0.0.1:6543/api/v1/produk

# GET
GET {{baseUrl}}

### create
POST {{baseUrl}}

{
    "nama": "nama produk",
    "harga": 10000,
    "stok": 10,
    "deskripsi": "deskripsi produk",
    "gambar": "gambar produk"
}

### update
PUT {{baseUrl}}

{
    "id": 12,
    "nama": "rt",
    "harga": 10000,
    "stok": 10,
    "deskripsi": "deskripsi produk",
    "gambar": "gambar produk"
}

### cek harga
POST {{baseUrl}}/jumlah_harga

{
    "id": [14, 14, 14]
}

### delete
DELETE {{baseUrl}}